[env]
framework = arduino
board_microros_transport = serial
board_microros_distro = ${sysenv.ROS_DISTRO}
monitor_speed = 921600
monitor_port = /dev/ttyACM0
lib_deps =
    https://github.com/micro-ROS/micro_ros_platformio
    PaulStoffregen/Time
    EEPROM
    http://www.airspayce.com/mikem/arduino/AccelStepper/AccelStepper-1.66.zip
    https://github.com/br3ttb/Arduino-PID-Library.git
    https://github.com/Hedrahexon/X9C103S.git

build_flags =
    '-D LOCAL_MAC={ 0xAA, 0xBB, 0xCC, 0xEE, 0xDD, 0xFF }'
    '-D LOCAL_IP={ 192, 168, 1, 101 }'
    '-D AGENT_IP={ 192, 168, 1, 100 }'
    '-D AGENT_PORT=8888'
    '-D WIFI_SSID="Oneplus"'
    '-D WIFI_PASSWORD="yash1713"'

; Serial platforms

[env:portenta_h7_m7]
platform = ststm32
board = portenta_h7_m7

[env:teensy41]
platform = teensy
board = teensy41
upload_protocol = teensy-cli

[env:teensy40]
platform = teensy
board = teensy40
upload_protocol = teensy-cli

[env:teensy36]
platform = teensy
board = teensy36
upload_protocol = teensy-cli

[env:teensy35]
platform = teensy
board = teensy35
upload_protocol = teensy-cli

[env:teensy31]
platform = teensy
board = teensy31
upload_protocol = teensy-cli

[env:due]
platform = atmelsam
board = due
build_flags =
    -D ARDUINO_DUE

[env:zero]
platform = atmelsam
board = zero

[env:olimex_e407]
platform = ststm32
board = olimex_e407

[env:esp32]
platform = espressif32
board = nodemcu-32s
board_microros_user_meta = ../platformio/action.meta
monitor_port = /dev/ttyUSB0

[env:lolin_s2_mini]
platform = espressif32
board = lolin_s2_mini

[env:nanorp2040connect]
platform = raspberrypi
board = nanorp2040connect
lib_ldf_mode = chain+

[env:pico]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = rpipico
board_build.core = earlephilhower
lib_ldf_mode = chain+
board_microros_user_meta = ../platformio/atomic.meta

[env:pico2]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = rpipico2
board_build.core = earlephilhower
lib_ldf_mode = chain+
board_microros_user_meta = ../platformio/atomic.meta

[env:esp32s3]
platform = espressif32
board = esp32-s3-devkitc-1
; board_microros_transport = serial
; board_microros_config = colcon.meta
build_flags =
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1

[env:esp32c3]
platform = espressif32
board = esp32-c3-devkitm-1

; Ethernet platforms

[env:teensy41_eth]
platform = teensy
board = teensy41
board_microros_transport = native_ethernet
lib_ldf_mode = chain+

; WiFi platforms

[env:portenta_h7_m7_wifi]
platform = ststm32
board = portenta_h7_m7
board_microros_transport = wifi
lib_ldf_mode = chain+

[env:esp32_wifi]
platform = espressif32
board = nodemcu-32s
board_microros_transport = wifi
board_microros_user_meta = ../platformio/action.meta
monitor_port = /dev/ttyUSB0
lib_ldf_mode = chain+

[env:nanorp2040connect_wifi]
platform = raspberrypi
board = nanorp2040connect
board_microros_transport = wifi_nina
lib_ldf_mode = chain+
lib_deps =
    ${env.lib_deps}
    arduino-libraries/WiFiNINA
