[platformio]
extra_configs =
    ../platformio/platformio.ini

; [env:esp32s3]
; platform = espressif32

; framework = arduino

; board = esp32-s3-devkitc-1

; build_flags =
;     -D ARDUINO_USB_CDC_ON_BOOT=1
;     -D ARDUINO_USB_MODE=1


; lib_deps =
;   micro_ros_platformio

; monitor_speed = 115200